packages:
  - packages/page-controller
  - packages/llms
  - packages/core
  - packages/page-agent
  - packages/mcp
  - packages/extension

allowBuilds:
  esbuild: true
  spawn-sync: true

ignoreScripts: false

onlyBuiltDependencies:
  - esbuild
  - spawn-sync
